-- =============================================================================
-- FastLane TMS — Phase 1.4: transactional tables
-- =============================================================================
-- All transactional tables carry created_at/updated_at + created_by/updated_by.
-- request_no and waybill_no are human-readable, auto-generated by triggers
-- (see automation migration). Waybills persist a self-contained SNAPSHOT so
-- historical documents never change when master data changes later.
-- =============================================================================

create sequence if not exists request_no_seq;

-- --- Transport requests -------------------------------------------------------
create table transport_requests (
  id                   uuid primary key default gen_random_uuid(),
  request_no           text not null unique,        -- TR-0001 (trigger-filled)
  client_id            uuid not null references clients (id),
  pickup_location_id   uuid references locations (id),
  delivery_location_id uuid references locations (id),
  shipment_type_id     uuid references shipment_types (id),
  truck_type_id        uuid references truck_types (id),
  quantity             numeric(12, 2),
  weight               numeric(12, 2),
  pallets              integer,
  required_pickup_at   timestamptz,
  delivery_date        date,
  special_instructions text,
  po_reference         text,
  status               request_status not null default 'Draft',
  approved_by          uuid references profiles (id),
  approved_at          timestamptz,
  rejected_reason      text,
  cancelled_at         timestamptz,
  created_by           uuid references profiles (id),
  updated_by           uuid references profiles (id),
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index transport_requests_status_idx on transport_requests (status);
create index transport_requests_client_idx on transport_requests (client_id);

create table request_items (
  id          uuid primary key default gen_random_uuid(),
  request_id  uuid not null references transport_requests (id) on delete cascade,
  item_name   text not null,
  description text,
  quantity    numeric(12, 2),
  unit_price  numeric(12, 2),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index request_items_request_idx on request_items (request_id);

-- --- Dispatches ---------------------------------------------------------------
-- Concurrency: optimistic guard = compare-and-swap on status + `version`
-- (bumped by trigger). "Issue" is NOT a status — flagged via has_issue at any
-- stage so the dispatch keeps its place in the flow.
create table dispatches (
  id                uuid primary key default gen_random_uuid(),
  request_id        uuid not null references transport_requests (id),
  assignment_type   assignment_type not null,
  truck_id          uuid references trucks (id),
  driver_id         uuid references drivers (id),
  supplier_id       uuid references suppliers (id),
  supplier_truck    text,
  truck_type_id     uuid references truck_types (id),
  status            dispatch_status not null default 'Assigned',
  version           integer not null default 0,
  has_issue         boolean not null default false,
  issue_note        text,
  issue_resolved_at timestamptz,
  dispatched_at     timestamptz,
  picked_up_at      timestamptz,
  delivered_at      timestamptz,
  ready_for_billing boolean not null default false,   -- Phase 7 hook
  closed_at         timestamptz,                       -- Phase 7 hook
  notes             text,
  created_by        uuid references profiles (id),
  updated_by        uuid references profiles (id),
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create index dispatches_request_idx on dispatches (request_id);
create index dispatches_status_idx on dispatches (status);
create index dispatches_driver_idx on dispatches (driver_id);

-- --- Waybills (self-contained snapshot) ---------------------------------------
create table waybills (
  id                  uuid primary key default gen_random_uuid(),
  waybill_no          text not null unique,          -- WB-YYYYMMDD-TR-0001
  dispatch_id         uuid not null unique references dispatches (id),
  request_id          uuid not null references transport_requests (id),
  status              waybill_status not null default 'draft',
  issued_at           timestamptz,
  approved_by         uuid references profiles (id),
  approved_at         timestamptz,
  -- Snapshot fields (copied at creation; never joined to live master data) ----
  client_name         text,
  pickup_address      text,
  delivery_address    text,
  truck_number        text,
  truck_type_name     text,
  shipment_type_name  text,
  quantity            numeric(12, 2),
  pickup_date         date,
  supplier_name       text,
  driver_name         text,
  created_by          uuid references profiles (id),
  updated_by          uuid references profiles (id),
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index waybills_request_idx on waybills (request_id);

create table waybill_pdfs (
  id           uuid primary key default gen_random_uuid(),
  waybill_id   uuid not null references waybills (id) on delete cascade,
  storage_path text not null,
  file_name    text,
  generated_at timestamptz not null default now()
);
create index waybill_pdfs_waybill_idx on waybill_pdfs (waybill_id);

-- --- Proof of delivery --------------------------------------------------------
create table pods (
  id           uuid primary key default gen_random_uuid(),
  dispatch_id  uuid not null references dispatches (id) on delete cascade,
  kind         pod_kind not null,
  storage_path text,
  note         text,
  uploaded_by  uuid references profiles (id),
  uploaded_at  timestamptz not null default now()
);
create index pods_dispatch_idx on pods (dispatch_id);

-- --- Exceptions (delay / damage / complaint) ----------------------------------
create table exceptions (
  id          uuid primary key default gen_random_uuid(),
  request_id  uuid references transport_requests (id) on delete cascade,
  dispatch_id uuid references dispatches (id) on delete cascade,
  kind        exception_kind not null,
  description text,
  reported_by uuid references profiles (id),
  resolved_at timestamptz,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create index exceptions_request_idx on exceptions (request_id);
create index exceptions_dispatch_idx on exceptions (dispatch_id);

-- --- Status history (operational visibility + audit) --------------------------
create table status_history (
  id          uuid primary key default gen_random_uuid(),
  entity      text not null,                 -- 'request' | 'dispatch'
  entity_id   uuid not null,
  from_status text,
  to_status   text not null,
  changed_by  uuid references profiles (id),
  changed_at  timestamptz not null default now()
);
create index status_history_entity_idx on status_history (entity, entity_id);
